# -*- coding: utf-8 -*-
"""Making Mozilla DeepSpeech language model & binary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhgBD5Vf4_fTdhafrTl1rZr5QI4YmR4I

## Preparation
([guide](https://github.com/mozilla/DeepSpeech#training-your-own-model))
"""

#Find and replace (ctrl+H) "ru-RU" and "Colab 1" with prefered names for voice dataset and your google drive folder respectively, if you want to
#You should create folder with chosen name at your google drive

#It is recommended to use google drive, because loading dataset every time is slow
from google.colab import drive
drive.mount('/content/drive')

!pip install folium==0.2.1
!pip install imgaug==0.2.5
!pip install albumentations==0.1.12
!pip install datascience==0.10.6
!pip install deepspeech
!apt install sox
!apt install libsox-dev
!git clone https://github.com/mozilla/DeepSpeech.git
!pip3 install -r DeepSpeech/requirements.txt
!pip3 install $(python3 DeepSpeech/util/taskcluster.py --decoder)

#Execute this cell only for the first time.
# %cd '/content/drive/My Drive/Colab 1/'
!wget #get address of your dataset from https://voice.mozilla.org/datasets and insert here
!mkdir 'ru-RU'
# %cd 'ru-RU'
!tar -xzvf '../ru.tar.gz'
# %cd /content
!DeepSpeech/bin/import_cv2.py '/content/drive/My Drive/Colab 1/ru-RU'

"""## Preparation for binaries
([guide](https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md))
"""

!git clone https://github.com/mozilla/tensorflow.git
# %cd tensorflow
!git checkout origin/r1.14
# %cd /content

!apt-get install pkg-config zip g++ zlib1g-dev unzip python3
!wget https://github.com/bazelbuild/bazel/releases/download/0.25.2/bazel-0.25.2-installer-linux-x86_64.sh
!chmod +x bazel-0.25.2-installer-linux-x86_64.sh
!./bazel-0.25.2-installer-linux-x86_64.sh

# %cd tensorflow
!./configure
#Default paths? What to support?
# %cd /content

# %cd tensorflow
!ln -s ../DeepSpeech/native_client ./

!bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie

